<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CarsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cars')->delete();

        DB::table('cars')->insert([
            // Carro 1
            [
                'id' => 1,
                'deleted_at' => '2025-09-19 09:13:54',
                'chassi' => '11111',
                'category' => 'Economy',
                'models_id' => 8,
                'color_id' => 4,
                'brand_id' => 1, // Kia
                'fuel_id' => 1,
                'manufacture_date' => 2016,
                'supplier_id' => 1,
                'mileage' => 40,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '60',
                'transmission' => 'Manual',
                'registration_date' => '2025-09-08',
                'observations' => 'Um carro ótimo para o dia-à-dia.',
                'license_plate' => 'LD-01-01-KL',
                'image' => '1757334779_image.jfif',
                'car_insurance' => '11111',
                'type_car' => 'sedan',
                'car_insurance_upload' => '1757334779_insurance.pdf',
                'car_document' => '11111',
                'car_document_upload' => '1757334779_document.pdf',
                'inspection_date' => '2025-06-04',
                'inspection_document_upload' => '1757334779_inspection.pdf',
                'price' => '32000.00',
                'created_at' => '2025-09-08 12:32:59',
                'updated_at' => '2025-09-19 09:13:54',
                'status' => 'available',
                'slug' => 'kia-picanto-2016',
            ],

            // Carro 2
            [
                'id' => 2,
                'deleted_at' => '2025-09-19 09:16:21',
                'chassi' => '22222',
                'category' => 'Economy',
                'models_id' => 2,
                'color_id' => 2,
                'brand_id' => 2, // Hyundai
                'fuel_id' => 4,
                'manufacture_date' => 2017,
                'type_car' => 'suv',
                'supplier_id' => 1,
                'mileage' => 80,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '65',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-08',
                'observations' => 'Prático para dias corridos.',
                'license_plate' => 'LD-02-02-HD',
                'image' => '1757334946_image.jfif',
                'car_insurance' => '22222',
                'car_insurance_upload' => '1757334946_insurance.pdf',
                'car_document' => '22222',
                'car_document_upload' => '1757334946_document.pdf',
                'inspection_date' => '2025-01-16',
                'inspection_document_upload' => '1757334946_inspection.pdf',
                'price' => '30000.00',
                'created_at' => '2025-09-08 12:35:46',
                'updated_at' => '2025-09-19 09:16:21',
                'status' => 'available',
                'slug' => 'hyundai-tucson-2017',
            ],

            // Carro 3
            [
                'id' => 3,
                'deleted_at' => null,
                'chassi' => '33333',
                'category' => 'Economy',
                'models_id' => 4,
                'color_id' => 3,
                'brand_id' => 4, // Suzuki
                'fuel_id' => 1,
                'manufacture_date' => 2019,
                'supplier_id' => 1,
                'mileage' => 70,
                'type_car' => 'compact',
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'engine' => '75',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-09',
                'observations' => 'O carro ideal para serviços privados.',
                'license_plate' => 'LD-03-03-HD',
                'image' => '1757420207_image.jfif',
                'car_insurance' => '33333',
                'car_insurance_upload' => '1757420207_insurance.pdf',
                'car_document' => '33333',
                'car_document_upload' => '1757420207_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757420207_inspection.pdf',
                'price' => '40000.00',
                'created_at' => '2025-09-09 12:16:47',
                'updated_at' => '2025-09-09 12:16:47',
                'status' => 'available',
                'slug' => 'suzuki-swift-2019',
            ],

            // Carro 4
            [
                'id' => 4,
                'deleted_at' => null,
                'chassi' => '44444',
                'category' => 'Economy',
                'models_id' => 3,
                'color_id' => 2,
                'brand_id' => 4, // Suzuki
                'fuel_id' => 4,
                'manufacture_date' => 2017,
                'supplier_id' => 1,
                'mileage' => 50,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'sports_car',
                'engine' => '76',
                'transmission' => 'Manual',
                'registration_date' => '2025-09-09',
                'observations' => 'Carro simples e muito económico.',
                'license_plate' => 'LD-04-04-HD',
                'image' => '1757420476_image.jfif',
                'car_insurance' => '44444',
                'car_insurance_upload' => '1757420476_insurance.pdf',
                'car_document' => '44444',
                'car_document_upload' => '1757420476_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757420476_inspection.pdf',
                'price' => '35000.00',
                'created_at' => '2025-09-09 12:21:16',
                'updated_at' => '2025-09-19 09:14:34',
                'status' => 'available',
                'slug' => 'suzuki-vitara-2017',
            ],

            // Carro 5
            [
                'id' => 5,
                'deleted_at' => '2025-09-19 09:14:08',
                'chassi' => '55555',
                'category' => 'Standard',
                'models_id' => 5,
                'color_id' => 4,
                'brand_id' => 2, // Hyundai
                'fuel_id' => 1,
                'manufacture_date' => 2018,
                'supplier_id' => 2,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'sports_car',
                'engine' => '78',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-09',
                'observations' => 'Garante mais segurança e possui maior conforto!',
                'license_plate' => 'LD-05-05-HD',
                'image' => '1757420664_image.jfif',
                'car_insurance' => '55555',
                'car_insurance_upload' => '1757420664_insurance.pdf',
                'car_document' => '55555',
                'car_document_upload' => '1757420664_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757420664_inspection.pdf',
                'price' => '50000.00',
                'created_at' => '2025-09-09 12:24:24',
                'updated_at' => '2025-09-19 09:14:08',
                'status' => 'available',
                'slug' => 'hyundai-elantra-2018',
            ],

            // Carro 6
            [
                'id' => 6,
                'deleted_at' => null,
                'chassi' => '66666',
                'category' => 'Standard',
                'models_id' => 6,
                'color_id' => 2,
                'brand_id' => 3, // Toyota
                'fuel_id' => 4,
                'manufacture_date' => 2019,
                'supplier_id' => 2,
                'mileage' => 80,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'minivan',
                'engine' => '75',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-09',
                'observations' => 'Carro potente e sofisticado.',
                'license_plate' => 'LD-06-06-HD',
                'image' => '1757421754_image.jfif',
                'car_insurance' => '66666',
                'car_insurance_upload' => '1757421754_insurance.pdf',
                'car_document' => '66666',
                'car_document_upload' => '1757421754_document.pdf',
                'inspection_date' => '2025-09-09',
                'inspection_document_upload' => '1757421754_inspection.pdf',
                'price' => '55000.00',
                'created_at' => '2025-09-09 12:42:34',
                'updated_at' => '2025-09-09 12:42:34',
                'status' => 'available',
                'slug' => 'toyota-innova-2019',
            ],

            // Carro 14
            [
                'id' => 14,
                'deleted_at' => null,
                'chassi' => '10101010',
                'category' => 'Economy',
                'models_id' => 8,
                'color_id' => 3,
                'brand_id' => 1, // Kia
                'fuel_id' => 4,
                'manufacture_date' => 2017,
                'supplier_id' => 1,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'compact_suv',
                'engine' => '240 kva',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-19',
                'observations' => 'Carro simples e muito sofisticado.',
                'license_plate' => 'LD-10-10-HD',
                'image' => '1758273600_image.jpg',
                'car_insurance' => '10101010',
                'car_insurance_upload' => '1758273600_insurance.pdf',
                'car_document' => '10101010',
                'car_document_upload' => '1758273600_document.pdf',
                'inspection_date' => '2025-09-19',
                'inspection_document_upload' => '1758273600_inspection.pdf',
                'price' => '40000.00',
                'created_at' => '2025-09-19 09:20:00',
                'updated_at' => '2025-09-19 09:20:00',
                'status' => 'available',
                'slug' => 'kia-sportage-2017',
            ],

            // Carro 15
            [
                'id' => 15,
                'deleted_at' => null,
                'chassi' => '12121212',
                'category' => 'Economy',
                'models_id' => 17,
                'color_id' => 2,
                'brand_id' => 1, // Kia
                'fuel_id' => 1,
                'manufacture_date' => 2020,
                'supplier_id' => 1,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'compact_suv',
                'engine' => '150 kva',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-19',
                'observations' => 'Carro muito seguro e sofisticado.',
                'license_plate' => 'LD-12-12-HD',
                'image' => '1758274082_image.jpg',
                'car_insurance' => '12121212',
                'car_insurance_upload' => '1758274082_insurance.pdf',
                'car_document' => '12121212',
                'car_document_upload' => '1758274082_document.pdf',
                'inspection_date' => '2025-09-19',
                'inspection_document_upload' => '1758274082_inspection.pdf',
                'price' => '80000.00',
                'created_at' => '2025-09-19 09:28:02',
                'updated_at' => '2025-09-19 09:28:02',
                'status' => 'available',
                'slug' => 'kia-seltos-2020',
            ],

            // Carro 16
            [
                'id' => 16,
                'deleted_at' => null,
                'chassi' => '13131313',
                'category' => 'Economy',
                'models_id' => 11,
                'color_id' => 2,
                'brand_id' => 2, // Hyundai
                'fuel_id' => 1,
                'manufacture_date' => 2017,
                'supplier_id' => 2,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'compact_suv',
                'engine' => '150 kva',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-19',
                'observations' => 'Útil para o dia-a-dia.',
                'license_plate' => 'LD-13-13-HD',
                'image' => '1758274238_image.jpg',
                'car_insurance' => '13131313',
                'car_insurance_upload' => '1758274238_insurance.pdf',
                'car_document' => '13131313',
                'car_document_upload' => '1758274238_document.pdf',
                'inspection_date' => '2025-09-19',
                'inspection_document_upload' => '1758274238_inspection.pdf',
                'price' => '30000.00',
                'created_at' => '2025-09-19 09:30:38',
                'updated_at' => '2025-09-19 09:30:38',
                'status' => 'available',
                'slug' => 'hyundai-creta-2017',
            ],

            // Carro 17
            [
                'id' => 17,
                'deleted_at' => null,
                'chassi' => '14141414',
                'category' => 'Economy',
                'models_id' => 18,
                'color_id' => 2,
                'brand_id' => 2, // Hyundai
                'fuel_id' => 1,
                'manufacture_date' => 2017,
                'supplier_id' => 2,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 5,
                'type_car' => 'suv',
                'engine' => '250 kva',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-19',
                'observations' => 'Lindo Carro.',
                'license_plate' => 'LD-14-14-HD',
                'image' => '1758274514_image.jpg',
                'car_insurance' => '14141414',
                'car_insurance_upload' => '1758274514_insurance.pdf',
                'car_document' => '14141414',
                'car_document_upload' => '1758274514_document.pdf',
                'inspection_date' => '2025-09-19',
                'inspection_document_upload' => '1758274514_inspection.pdf',
                'price' => '60000.00',
                'created_at' => '2025-09-19 09:35:14',
                'updated_at' => '2025-09-19 09:35:14',
                'status' => 'available',
                'slug' => 'hyundai-santa-fe-2017',
            ],

            // Carro 18
            [
                'id' => 18,
                'deleted_at' => null,
                'chassi' => '15151515',
                'category' => 'Luxury',
                'models_id' => 19,
                'color_id' => 2,
                'brand_id' => 16, // Lexus
                'fuel_id' => 3,
                'manufacture_date' => 2022,
                'supplier_id' => 1,
                'mileage' => 0,
                'number_of_doors' => 5,
                'number_of_seats' => 7,
                'type_car' => 'coupe',
                'engine' => '350 kva',
                'transmission' => 'Automático',
                'registration_date' => '2025-09-19',
                'observations' => 'Carro luxuoso e muito confortável.',
                'license_plate' => 'LD-15-15-HD',
                'image' => '1758274834_image.jpg',
                'car_insurance' => '15151515',
                'car_insurance_upload' => '1758274834_insurance.pdf',
                'car_document' => '15151515',
                'car_document_upload' => '1758274834_document.pdf',
                'inspection_date' => '2025-09-19',
                'inspection_document_upload' => '1758274834_inspection.pdf',
                'price' => '120000.00',
                'created_at' => '2025-09-19 09:40:34',
                'updated_at' => '2025-09-19 09:40:34',
                'status' => 'available',
                'slug' => 'lexus-lc-2022',
            ],

            // Carro 19
            [
                'id' => 19,
                'deleted_at' => null,
                'chassi' => '16161616',
                'category' => 'Standard',
                'models_id' => 16,
                'color_id' => 3,
                'brand_id' => 3, // Toyota
                'fuel_id' => 3,
                'manufacture_date' => 2018,
                'supplier_id' => 1,
                'mileage' => 0,
                'number_of_doors' => 4,
                'number_of_seats' => 5,
                'type_car' => 'station_wagon',
                'engine' => '450 kva',
                'transmission' => 'Manual',
                'registration_date' => '2025-09-19',
                'observations' => 'Carro todo terreno, útil para grandes viagens.',
                'license_plate' => 'LD-16-16-HD',
                'image' => '1758275074_image.jpg',
                'car_insurance' => '16161616',
                'car_insurance_upload' => '1758275074_insurance.pdf',
                'car_document' => '16161616',
                'car_document_upload' => '1758275074_document.pdf',
                'inspection_date' => '2025-09-19',
                'inspection_document_upload' => '1758275074_inspection.pdf',
                'price' => '90000.00',
                'created_at' => '2025-09-19 09:44:34',
                'updated_at' => '2025-09-19 09:44:34',
                'status' => 'available',
                'slug' => 'toyota-corolla-touring-2018',
            ],
        ]);
    }
}